[build]
  command = "npm run build"
  publish = "out"

# Handle static file serving
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Handle 404s
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = true 